# Generated by Django 4.2.6 on 2023-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique per coordination: institution.campus-course', max_length=50, unique=True, verbose_name='Código')),
                ('course', models.CharField(max_length=50, verbose_name='Curso')),
                ('institution', models.CharField(max_length=50, verbose_name='Instituição')),
                ('campus', models.CharField(max_length=50, verbose_name='Campus')),
            ],
        ),
    ]
