# Generated by Django 4.2.6 on 2023-11-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coordination'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='coordination',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=50, verbose_name='Senha'),
        ),
    ]
