# Generated by Django 4.2.6 on 2023-11-15 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_coordination_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100, verbose_name='Título do projeto')),
                ('status', models.CharField(choices=[('C', 'Concluída'), ('I', 'Interrompida'), ('A', 'Em andamento')], max_length=50, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de início')),
                ('guidance_code', models.CharField(max_length=6, unique=True, verbose_name='Código Da Orientação')),
                ('advisor', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.advisor', verbose_name='Orientador')),
                ('coordination', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.coordination', verbose_name='Coordenação')),
                ('student', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Estudante')),
            ],
        ),
    ]
