# Generated by Django 4.2.6 on 2023-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='status',
            field=models.CharField(default='Em andamento', max_length=50, verbose_name='Status'),
        ),
    ]
