# Generated by Django 4.2.6 on 2023-11-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidances', '0003_alter_guidance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidance',
            name='project_title',
            field=models.CharField(max_length=150, verbose_name='Título do projeto'),
        ),
    ]
